GET http://localhost:3000/

###
PUT  http://localhost:3000/profile/
Content-Type: application/json

{
    "account_id": "A34ba834d37851c826d079cff357c7582",
    "name": "etse@mail.deede",
    "image" : "passsserdede"
}



###
DELETE   http://localhost:3000/profile?profile_id=P7bd937b8444cb8f832867508177f9231



###
DELETE   http://localhost:3000/profile?profile_id=Pe3368027c5d7d71617a62bb77603b5c1

###
PUT  http://localhost:3000/profile/bookmark?profile_id=P0bb08f3bcd88edad30d9a707f3dacaca&movie_id=M370e1f2dc5084f39bbd7bc542d876661

###
PUT  http://localhost:3000/profile/favorite?profile_id=P0bb08f3bcd88edad30d9a707f3dacaca&movie_id=M370e1f2dc5084f39bbd7bc542d876661

###
DELETE   http://localhost:3000/profile/bookmark?profile_id=P0bb08f3bcd88edad30d9a707f3dacaca&movie_id=M370e1f2dc5084f39bbd7bc542d876661

###
DELETE   http://localhost:3000/profile/favorite?profile_id=P0bb08f3bcd88edad30d9a707f3dacaca&movie_id=M370e1f2dc5084f39bbd7bc542d876661


###
POST   http://localhost:3000/profile/history/?profile_id=P0bb08f3bcd88edad30d9a707f3dacaca&movie_id=Mb638c130492bf33679c8f6e797ca1125&timestamp=80

###
GET   http://localhost:3000/profile/overallwatchtime/?profile_id=P0bb08f3bcd88edad30d9a707f3dacaca

###
GET   http://localhost:3000/profile/genrewatchtime/?profile_id=P0bb08f3bcd88edad30d9a707f3dacaca




###
DELETE   http://localhost:3000/profile?profile_id=Pe3368027c5d7d71617a62bb77603b5c1&a=b

###
PUT  http://localhost:3000/profile/bookmark?profile_id=P0bb08f3bcd88edad30d9a707f3dacaca&movie_id=M370e1f2dc5084f39bbd7bc542d876661&a=b

###
PUT  http://localhost:3000/profile/favorite?profile_id=P0bb08f3bcd88edad30d9a707f3dacaca&movie_id=M370e1f2dc5084f39bbd7bc542d876661&a=b

###
POST   http://localhost:3000/profile/history/?profile_id=P0bb08f3bcd88edad30d9a707f3dacaca&movie_id=Mb638c130492bf33679c8f6e797ca1125&timestamp=80&a=b

###
GET   http://localhost:3000/profile/overallwatchtime/?profile_id=P0bb08f3bcd88edad30d9a707f3dacaca&a=b

###
GET   http://localhost:3000/profile/genrewatchtime/?profile_id=P0bb08f3bcd88edad30d9a707f3dacaca&a=b

